// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TermWeight.proto

package org.apache.accumulo.examples.wikisearch.protobuf;

public final class TermWeight {
  private TermWeight() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float normalizedTermFrequency = 1;
    /**
     * <code>required float normalizedTermFrequency = 1;</code>
     */
    boolean hasNormalizedTermFrequency();
    /**
     * <code>required float normalizedTermFrequency = 1;</code>
     */
    float getNormalizedTermFrequency();

    // repeated uint32 wordOffset = 2;
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    java.util.List<java.lang.Integer> getWordOffsetList();
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    int getWordOffsetCount();
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    int getWordOffset(int index);
  }
  /**
   * Protobuf type {@code org.apache.accumulo.examples.wikisearch.protobuf.Info}
   */
  public static final class Info extends
      com.google.protobuf.GeneratedMessage
      implements InfoOrBuilder {
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Info defaultInstance;
    public static Info getDefaultInstance() {
      return defaultInstance;
    }

    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              normalizedTermFrequency_ = input.readFloat();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                wordOffset_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              wordOffset_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                wordOffset_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                wordOffset_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          wordOffset_ = java.util.Collections.unmodifiableList(wordOffset_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.class, org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.Builder.class);
    }

    public static com.google.protobuf.Parser<Info> PARSER =
        new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required float normalizedTermFrequency = 1;
    public static final int NORMALIZEDTERMFREQUENCY_FIELD_NUMBER = 1;
    private float normalizedTermFrequency_;
    /**
     * <code>required float normalizedTermFrequency = 1;</code>
     */
    public boolean hasNormalizedTermFrequency() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float normalizedTermFrequency = 1;</code>
     */
    public float getNormalizedTermFrequency() {
      return normalizedTermFrequency_;
    }

    // repeated uint32 wordOffset = 2;
    public static final int WORDOFFSET_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> wordOffset_;
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getWordOffsetList() {
      return wordOffset_;
    }
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    public int getWordOffsetCount() {
      return wordOffset_.size();
    }
    /**
     * <code>repeated uint32 wordOffset = 2;</code>
     */
    public int getWordOffset(int index) {
      return wordOffset_.get(index);
    }

    private void initFields() {
      normalizedTermFrequency_ = 0F;
      wordOffset_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNormalizedTermFrequency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, normalizedTermFrequency_);
      }
      for (int i = 0; i < wordOffset_.size(); i++) {
        output.writeUInt32(2, wordOffset_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, normalizedTermFrequency_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < wordOffset_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(wordOffset_.get(i));
        }
        size += dataSize;
        size += 1 * getWordOffsetList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.accumulo.examples.wikisearch.protobuf.Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.class, org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.Builder.class);
      }

      // Construct using org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        normalizedTermFrequency_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        wordOffset_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor;
      }

      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info getDefaultInstanceForType() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.getDefaultInstance();
      }

      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info build() {
        org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info buildPartial() {
        org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info result = new org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.normalizedTermFrequency_ = normalizedTermFrequency_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          wordOffset_ = java.util.Collections.unmodifiableList(wordOffset_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.wordOffset_ = wordOffset_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info) {
          return mergeFrom((org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info other) {
        if (other == org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.getDefaultInstance()) return this;
        if (other.hasNormalizedTermFrequency()) {
          setNormalizedTermFrequency(other.getNormalizedTermFrequency());
        }
        if (!other.wordOffset_.isEmpty()) {
          if (wordOffset_.isEmpty()) {
            wordOffset_ = other.wordOffset_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWordOffsetIsMutable();
            wordOffset_.addAll(other.wordOffset_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNormalizedTermFrequency()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float normalizedTermFrequency = 1;
      private float normalizedTermFrequency_ ;
      /**
       * <code>required float normalizedTermFrequency = 1;</code>
       */
      public boolean hasNormalizedTermFrequency() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float normalizedTermFrequency = 1;</code>
       */
      public float getNormalizedTermFrequency() {
        return normalizedTermFrequency_;
      }
      /**
       * <code>required float normalizedTermFrequency = 1;</code>
       */
      public Builder setNormalizedTermFrequency(float value) {
        bitField0_ |= 0x00000001;
        normalizedTermFrequency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float normalizedTermFrequency = 1;</code>
       */
      public Builder clearNormalizedTermFrequency() {
        bitField0_ = (bitField0_ & ~0x00000001);
        normalizedTermFrequency_ = 0F;
        onChanged();
        return this;
      }

      // repeated uint32 wordOffset = 2;
      private java.util.List<java.lang.Integer> wordOffset_ = java.util.Collections.emptyList();
      private void ensureWordOffsetIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          wordOffset_ = new java.util.ArrayList<java.lang.Integer>(wordOffset_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getWordOffsetList() {
        return java.util.Collections.unmodifiableList(wordOffset_);
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public int getWordOffsetCount() {
        return wordOffset_.size();
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public int getWordOffset(int index) {
        return wordOffset_.get(index);
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public Builder setWordOffset(
          int index, int value) {
        ensureWordOffsetIsMutable();
        wordOffset_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public Builder addWordOffset(int value) {
        ensureWordOffsetIsMutable();
        wordOffset_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public Builder addAllWordOffset(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureWordOffsetIsMutable();
        super.addAll(values, wordOffset_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 wordOffset = 2;</code>
       */
      public Builder clearWordOffset() {
        wordOffset_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.apache.accumulo.examples.wikisearch.protobuf.Info)
    }

    static {
      defaultInstance = new Info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.apache.accumulo.examples.wikisearch.protobuf.Info)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TermWeight.proto\0220org.apache.accumulo." +
      "examples.wikisearch.protobuf\";\n\004Info\022\037\n\027" +
      "normalizedTermFrequency\030\001 \002(\002\022\022\n\nwordOff" +
      "set\030\002 \003(\rB4\n0org.apache.accumulo.example" +
      "s.wikisearch.protobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_apache_accumulo_examples_wikisearch_protobuf_Info_descriptor,
              new java.lang.String[] { "NormalizedTermFrequency", "WordOffset", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
